# .github/workflows/docker-release.yml
name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do reposit√≥rio
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check out the code
        uses: action/checkout@v2

      - name: Get up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into  Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jogo_galo:${{ github.ref_name }}
        
